tdd_todo/config/routes.rb
Rails.application.routes.draw do
  root "welcomes#index"
  resources :todos
  resources :sessions, only: [:new, :create]
end

tdd_todo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tdd_todo/app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  enum state: %i[incomplete complete]
end

tdd_todo/app/models/user.rb
class User < ApplicationRecord
  has_many :todos
end

tdd_todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def auth_user
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def logged_in?
    !session[:user_id].blank?
  end

  def current_user
    if logged_in?
      @current_user ||= User.find(session[:user_id])
    else
      nil
    end
  end

end

tdd_todo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(username: params[:username], password: params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to todos_path
    else
      flash[:notice] = "用户名密码不正确"
      render action: :new
    end
  end

end

tdd_todo/app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :auth_user

  def index
    @todos = current_user.todos.order("id desc")
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.new(params.require(:todo).permit(:title))
    if @todo.save
      redirect_to todos_path
    else
      render action: :new
    end
  end

  def update
    @todo = current_user.todos.find(params[:id])
    @todo.incomplete? ? @todo.complete! : @todo.incomplete!
    redirect_back(fallback_location: todos_path)
  end
end

tdd_todo/app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

tdd_todo/app/helpers/application_helper.rb
module ApplicationHelper
end

tdd_todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddTodo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tdd_todo/app/views/todos/index.html.erb
<h1>Todos list</h1>

<%= link_to "Create a Todo", new_todo_path %>

<ul>
  <% @todos.each do |todo| %>
    <li id="todo-<%= todo.id %>">
      <span class="<%= todo.complete? ? 'complete' : 'incomplete' %>">
        <%= todo.complete? ? '已完成' : '未完成' %>
      </span>
      <%= todo.title %>
      <%= link_to "#{todo.complete? ? '设为未完成' : '设为已完成'}", todo_path(todo), method: :put %>
    </li>
  <% end %>
</ul>

tdd_todo/app/views/todos/new.html.erb
<h1>Create a Todo</h1>

<%= form_for @todo, url: todos_path, html: { id: 'todo-form' } do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "Save" %>
<% end %>

tdd_todo/app/views/welcomes/index.html.erb
hello world